name: 'Get Core Dependencies'
description: 'sets the node version & initializes core dependencies'
runs:
  using: composite
  steps:
    - name: Use Node from NVM
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      shell: bash
